version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: always


volumes:
  sqlite_data: