version: '3.8'  # Docker Compose version

services:
  app:
    build: .  # Build from current directory
    ports:
      - "5001:5000"
    volumes:
      - sqlite_data:/app/data  # Persist SQLite data
    environment:
      - FLASK_ENV=development  # Set Flask environment to development mode
      - FLASK_APP=app.py  # Define the main Flask application file
    restart: always  # Auto-restart on failure

volumes:
  sqlite_data:  # Named volume for data persistence